<a href="https://colab.research.google.com/github/sodan97/codes/blob/main/ANN_phishing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Importing the libraries


In [61]:
import numpy as np
import pandas as pd
import tensorflow as tf

# Part 1: Data Preprocessing

### Importing the dataset

In [62]:
dataset = pd.read_csv("/content/PhiUSIIL_Phishing_URL_Dataset.csv")
X = dataset.iloc[:, 4:-1].values
y = dataset.iloc[:, -1].values

#print(np.length(X))
#print(f'cat: {X[:,2]} et {X[:,25]}')

# Delete categorical variables
delete_columns = [2, 25]
X = np.delete(X, delete_columns, axis=1)
#print(X)

### Splitting the dataset

In [63]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.2, random_state= 0)

### Feature scaling

In [64]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
print(f'X = {X} \n col = {np.size(X[0])} \n line = {np.size(X[:,0])}')
print(f'\n {len(X)} \n {X_train.shape}')


X = [[24 0 100.0 ... 119 0 124]
 [16 0 100.0 ... 39 0 217]
 [22 0 100.0 ... 42 2 5]
 ...
 [23 0 100.0 ... 58 2 67]
 [47 0 28.15753735 ... 0 0 0]
 [26 0 100.0 ... 256 0 261]] 
 col = 49 
 line = 235795

 235795 
 (188636, 49)


### Encoding categorical data

# Part 2: Building the ANN

### Initialization

In [65]:
model = tf.keras.models.Sequential()

### [Adding the input layer and the first hidden layer]

In [66]:
model.add(tf.keras.layers.Dense(units=16, activation='relu'))
model.add(tf.keras.layers.Dropout(0.5))

### Adding the second hidden layer

In [67]:
model.add(tf.keras.layers.Dense(units=16, activation='relu'))
model.add(tf.keras.layers.Dropout(0.5))

### Adding the output layer

In [68]:
model.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Part 3: Training the ANN

### Compiling the ANN

In [69]:
model.compile(optimizer = 'adam', loss= 'mean_squared_error', metrics=['accuracy'] )

### Training the ANN model on the training dataset

In [70]:
model.fit(X_train, y_train, batch_size= 32, epochs= 3)

Epoch 1/3
5895/5895 [==============================] - 13s 2ms/step - loss: 0.0129 - accuracy: 0.9838
Epoch 2/3
5895/5895 [==============================] - 10s 2ms/step - loss: 0.0019 - accuracy: 0.9977
Epoch 3/3
5895/5895 [==============================] - 11s 2ms/step - loss: 0.0016 - accuracy: 0.9980


### Predicting the results of the Test dataset

In [71]:
y_pred = model.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

1474/1474 [==============================] - 3s 2ms/step
[[0 0]
 [1 1]
 [1 1]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Evaluating the ANN with Tensorflow


In [72]:
loss, accuracy = model.evaluate(X_test, y_test, verbose=0)
print(f"Précision du modèle: {accuracy*100:.2f}%")

Précision du modèle: 99.98%


### Evaluating the ANN with scikitlearn


In [73]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(f"cm = \n {cm}")
# rate of successful
pourcentage_reussite_test = (cm[0][0] + cm[1][1])/len(X_test)
print(pourcentage_reussite_test)


cm = 
 [[20190    10]
 [    1 26958]]
0.9997667465383065
